### ISSUE TITLE
Setup instructions?

### ISSUE THREAD

**Issue by ChillerDragon** [carlini/js13k2019-yet-another-doom-clone#1]
Would be nice if the readme could explain the code minifier provide some requirements.txt for make.py and add general setup/getting started instructions.

I got it somewhat running with these two commands:

```
python -m SimpleHTTPServer &
firefox http://localhost:8000/src/webgl.html
```

But it looked kinda buggy and the view was resizing randomly.

![image](https://user-images.githubusercontent.com/20344300/84915267-ddd0a480-b0bc-11ea-8bf2-87240b210196.png)

**Comment by carlini** [comment]
I've updated the README to be a more real readme. It should have better steps hopefully now.

**Comment by ChillerDragon** [comment]
Awesome thanks!
